// CSR (Client-Side Rendering) Example
// This page is rendered entirely in the browser
"use client";

import { useState, useEffect } from "react";
import CSRCounter from "@/components/csrCounter";

const CSRPage = () => {
  const [mounted, setMounted] = useState(false);
  const [clientTime, setClientTime] = useState<string>("");
  const [data, setData] = useState<{ message: string; id: string } | null>(
    null
  );

  useEffect(() => {
    // This runs only on the client
    setMounted(true);
    setClientTime(new Date().toISOString());

    // Simulate client-side data fetching
    setTimeout(() => {
      setData({
        message: "This data is fetched on the client browser",
        id: Math.random().toString(36).substring(7),
      });
    }, 500);
  }, []);

  if (!mounted) {
    return (
      <div style={{ padding: "20px", textAlign: "center" }}>
        <p>Loading... (Client-side rendering)</p>
      </div>
    );
  }

  return (
    <>
      <h3 className="commonHeading" style={{ marginTop: "20px" }}>
        CSR (Client-Side Rendering) Example
      </h3>
      <div
        style={{
          marginTop: "20px",
          padding: "20px",
          border: "2px solid #00d9ff",
          borderRadius: "8px",
        }}
      >
        <p style={{ marginBottom: "10px" }}>
          <strong>Rendering Type:</strong> Client-Side Rendering (CSR)
        </p>
        <p style={{ marginBottom: "10px" }}>
          <strong>When:</strong> Rendered entirely in the browser using
          JavaScript
        </p>
        <p style={{ marginBottom: "10px" }}>
          <strong>Client Render Time:</strong> {clientTime}
        </p>
        {data && (
          <>
            <p style={{ marginBottom: "10px" }}>
              <strong>Client Fetched ID:</strong> {data.id}
            </p>
            <p style={{ marginBottom: "10px", color: "#666" }}>
              {data.message}
            </p>
          </>
        )}
        <p style={{ marginBottom: "20px", color: "#666" }}>
          This page is rendered entirely in the browser. Check the page source
          (View Source) - you&apos;ll see minimal HTML with just a loading
          state. All content is generated by JavaScript after the page loads.
          The timestamp above is set when React hydrates on the client.
        </p>
        <CSRCounter />
      </div>
      <div style={{ marginTop: "20px" }}>
        <a
          href="/rendering-poc"
          style={{ color: "#00d9ff", textDecoration: "underline" }}
        >
          ← Back to Rendering POC
        </a>
      </div>
    </>
  );
};

export default CSRPage;
